---
- hosts: 192.168.1.184
  remote_user: root
  tasks:
    - name: start nginx
      service: name=nginx state=started
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted 
